#!/bin/bash

brew install graalvm/tap/graalvm-ce-lts-java11
brew install clojure/tools/clojure
brew install borkdude/brew/clj-kondo
brew install leiningen

lein --version
cp "${INCLUDES_ROOT}/lein/profiles.clj" /Users/gordon/.lein/profiles.clj
